// Curriculum modeled on the CEFR progression used by Rivstart (Natur & Kultur).
// Themes, grammar focus, and ordering follow the same pedagogical sequence,
// but all vocabulary, prompts, and scenarios are original.

export const CURRICULUM = [
  // ── A1 — beginner ──────────────────────────────────────────────
  {
    id: "a1-1",
    level: "A1",
    title: "Hej och hej då",
    theme: "Greetings and basic introductions",
    grammarFocus: "Present tense of att vara and att heta",
    vocabulary: [
      { sv: "hej", en: "hi" },
      { sv: "hej då", en: "goodbye" },
      { sv: "god morgon", en: "good morning" },
      { sv: "god kväll", en: "good evening" },
      { sv: "vad heter du?", en: "what's your name?" },
      { sv: "jag heter…", en: "my name is…" },
      { sv: "trevligt att träffas", en: "nice to meet you" },
      { sv: "hur mår du?", en: "how are you?" },
      { sv: "jag mår bra", en: "I'm doing well" },
      { sv: "tack", en: "thanks" },
      { sv: "varsågod", en: "you're welcome / here you go" },
      { sv: "ja", en: "yes" },
      { sv: "nej", en: "no" },
    ],
    scenario: "You meet a Swedish person for the first time at a fika in Göteborg.",
  },
  {
    id: "a1-2",
    level: "A1",
    title: "Om mig",
    theme: "Talking about yourself: where you're from, where you live",
    grammarFocus: "Subject pronouns (jag/du/han/hon/vi/ni/de) + att bo, att komma",
    vocabulary: [
      { sv: "var bor du?", en: "where do you live?" },
      { sv: "jag bor i…", en: "I live in…" },
      { sv: "var kommer du ifrån?", en: "where are you from?" },
      { sv: "jag kommer från…", en: "I'm from…" },
      { sv: "ett land", en: "a country" },
      { sv: "en stad", en: "a city" },
      { sv: "Sverige", en: "Sweden" },
      { sv: "Australien", en: "Australia" },
      { sv: "engelska", en: "English (language)" },
      { sv: "svenska", en: "Swedish (language)" },
      { sv: "att prata", en: "to speak" },
      { sv: "lite", en: "a little" },
      { sv: "mycket", en: "much / a lot" },
    ],
    scenario: "A new colleague asks where you're from and how long you've been in Sweden.",
  },
  {
    id: "a1-3",
    level: "A1",
    title: "Min familj",
    theme: "Family members and possessives",
    grammarFocus: "Possessive pronouns (min, din, hans, hennes, vår, er, deras)",
    vocabulary: [
      { sv: "en familj", en: "a family" },
      { sv: "en mamma", en: "a mum" },
      { sv: "en pappa", en: "a dad" },
      { sv: "en syster", en: "a sister" },
      { sv: "en bror", en: "a brother" },
      { sv: "ett barn", en: "a child" },
      { sv: "en son", en: "a son" },
      { sv: "en dotter", en: "a daughter" },
      { sv: "ett syskon", en: "a sibling" },
      { sv: "en partner", en: "a partner" },
      { sv: "gift", en: "married" },
      { sv: "singel", en: "single" },
      { sv: "ung", en: "young" },
      { sv: "gammal", en: "old" },
    ],
    scenario: "You're showing photos of your family to a friend over coffee.",
  },
  {
    id: "a1-4",
    level: "A1",
    title: "Vardagsrutiner",
    theme: "Daily routines and times",
    grammarFocus: "Telling time and present-tense regular verbs",
    vocabulary: [
      { sv: "att vakna", en: "to wake up" },
      { sv: "att gå upp", en: "to get up" },
      { sv: "att äta", en: "to eat" },
      { sv: "frukost", en: "breakfast" },
      { sv: "lunch", en: "lunch" },
      { sv: "middag", en: "dinner" },
      { sv: "att jobba / arbeta", en: "to work" },
      { sv: "att gå hem", en: "to go home" },
      { sv: "att sova", en: "to sleep" },
      { sv: "klockan sju", en: "at seven o'clock" },
      { sv: "halv åtta", en: "half past seven (7:30)" },
      { sv: "kvart över", en: "quarter past" },
      { sv: "kvart i", en: "quarter to" },
      { sv: "imorgon", en: "tomorrow" },
      { sv: "idag", en: "today" },
    ],
    scenario: "A coworker asks what a typical workday looks like for you.",
  },

  // ── A2 — elementary ───────────────────────────────────────────
  {
    id: "a2-1",
    level: "A2",
    title: "På restaurangen",
    theme: "Ordering food and drink",
    grammarFocus: "Modal verbs (vill, ska, kan) and polite ordering forms",
    vocabulary: [
      { sv: "en meny", en: "a menu" },
      { sv: "att beställa", en: "to order" },
      { sv: "en förrätt", en: "a starter" },
      { sv: "en huvudrätt", en: "a main course" },
      { sv: "en efterrätt", en: "a dessert" },
      { sv: "ett bord", en: "a table" },
      { sv: "en servitör / servitris", en: "a waiter / waitress" },
      { sv: "vad får det vara?", en: "what would you like?" },
      { sv: "jag skulle vilja ha…", en: "I would like…" },
      { sv: "kan jag få…?", en: "can I have…?" },
      { sv: "köttbullar", en: "meatballs" },
      { sv: "lax", en: "salmon" },
      { sv: "sallad", en: "salad" },
      { sv: "vatten", en: "water" },
      { sv: "ett glas vin", en: "a glass of wine" },
      { sv: "notan, tack", en: "the bill, please" },
    ],
    scenario: "You sit down at a restaurant in Stockholm for lunch. A waiter approaches.",
  },
  {
    id: "a2-2",
    level: "A2",
    title: "Att resa",
    theme: "Travel and transport",
    grammarFocus: "Prepositions of motion (till, från, med, på) + att åka",
    vocabulary: [
      { sv: "att resa", en: "to travel" },
      { sv: "att åka", en: "to go (by vehicle)" },
      { sv: "ett tåg", en: "a train" },
      { sv: "en buss", en: "a bus" },
      { sv: "en bil", en: "a car" },
      { sv: "en cykel", en: "a bicycle" },
      { sv: "ett flyg", en: "a flight" },
      { sv: "en biljett", en: "a ticket" },
      { sv: "en station", en: "a station" },
      { sv: "en hållplats", en: "a stop (bus/tram)" },
      { sv: "att hyra", en: "to rent" },
      { sv: "en resa", en: "a trip" },
      { sv: "en semester", en: "a holiday / vacation" },
      { sv: "att komma fram", en: "to arrive" },
      { sv: "att åka iväg", en: "to depart / set off" },
    ],
    scenario: "You're planning a weekend trip from Göteborg to Stockholm and asking about options.",
  },
  {
    id: "a2-3",
    level: "A2",
    title: "I affären",
    theme: "Shopping for groceries and clothes",
    grammarFocus: "Definite and indefinite forms; en/ett gender practice",
    vocabulary: [
      { sv: "en affär / en butik", en: "a shop" },
      { sv: "en mataffär", en: "a grocery store" },
      { sv: "ett pris", en: "a price" },
      { sv: "billig", en: "cheap" },
      { sv: "dyr", en: "expensive" },
      { sv: "rea", en: "sale" },
      { sv: "en storlek", en: "a size" },
      { sv: "att prova", en: "to try on" },
      { sv: "ett kvitto", en: "a receipt" },
      { sv: "att betala", en: "to pay" },
      { sv: "kontant", en: "cash" },
      { sv: "kort", en: "card" },
      { sv: "en tröja", en: "a jumper / sweater" },
      { sv: "byxor", en: "trousers" },
      { sv: "skor", en: "shoes" },
    ],
    scenario: "You're picking out a jumper at a clothing store and need to find your size.",
  },
  {
    id: "a2-4",
    level: "A2",
    title: "Hemma",
    theme: "Home, rooms, and household items",
    grammarFocus: "Prepositions of location (i, på, under, bredvid, framför)",
    vocabulary: [
      { sv: "en lägenhet", en: "an apartment" },
      { sv: "ett hus", en: "a house" },
      { sv: "ett rum", en: "a room" },
      { sv: "ett kök", en: "a kitchen" },
      { sv: "ett vardagsrum", en: "a living room" },
      { sv: "ett sovrum", en: "a bedroom" },
      { sv: "ett badrum", en: "a bathroom" },
      { sv: "en soffa", en: "a sofa" },
      { sv: "en säng", en: "a bed" },
      { sv: "ett bord", en: "a table" },
      { sv: "en stol", en: "a chair" },
      { sv: "ett fönster", en: "a window" },
      { sv: "en dörr", en: "a door" },
      { sv: "att hyra", en: "to rent" },
      { sv: "att äga", en: "to own" },
    ],
    scenario: "A Swedish friend has just moved and is describing their new apartment to you.",
  },
  {
    id: "a2-5",
    level: "A2",
    title: "Igår och förra veckan",
    theme: "Talking about past events",
    grammarFocus: "Preteritum (simple past) of common regular and irregular verbs",
    vocabulary: [
      { sv: "igår", en: "yesterday" },
      { sv: "i förra veckan", en: "last week" },
      { sv: "i förrgår", en: "the day before yesterday" },
      { sv: "en helg", en: "a weekend" },
      { sv: "jag åt", en: "I ate" },
      { sv: "jag drack", en: "I drank" },
      { sv: "jag gick", en: "I went / walked" },
      { sv: "jag såg", en: "I saw" },
      { sv: "jag pratade", en: "I spoke" },
      { sv: "jag jobbade", en: "I worked" },
      { sv: "jag träffade", en: "I met" },
      { sv: "rolig", en: "fun" },
      { sv: "tråkig", en: "boring" },
      { sv: "spännande", en: "exciting" },
    ],
    scenario: "It's Monday morning. A colleague asks how your weekend was.",
  },
  {
    id: "a2-6",
    level: "A2",
    title: "Vädret och årstiderna",
    theme: "Weather and seasons",
    grammarFocus: "Impersonal verbs (det regnar, det snöar) + adjective agreement",
    vocabulary: [
      { sv: "vädret", en: "the weather" },
      { sv: "en årstid", en: "a season" },
      { sv: "våren", en: "spring" },
      { sv: "sommaren", en: "summer" },
      { sv: "hösten", en: "autumn" },
      { sv: "vintern", en: "winter" },
      { sv: "det regnar", en: "it's raining" },
      { sv: "det snöar", en: "it's snowing" },
      { sv: "soligt", en: "sunny" },
      { sv: "molnigt", en: "cloudy" },
      { sv: "blåsigt", en: "windy" },
      { sv: "varmt", en: "warm" },
      { sv: "kallt", en: "cold" },
      { sv: "en grad", en: "a degree" },
      { sv: "minus tio", en: "minus ten" },
    ],
    scenario: "It's a grey November day. You're chatting about how this winter compares to last.",
  },
  {
    id: "a2-7",
    level: "A2",
    title: "Hälsa och kropp",
    theme: "Health, body parts, and visiting the doctor",
    grammarFocus: "Reflexive verbs (att må, att känna sig) and gör ont constructions",
    vocabulary: [
      { sv: "att må bra/dåligt", en: "to feel well/bad" },
      { sv: "sjuk", en: "sick" },
      { sv: "frisk", en: "healthy" },
      { sv: "en huvudvärk", en: "a headache" },
      { sv: "ont i magen", en: "stomach pain" },
      { sv: "feber", en: "fever" },
      { sv: "en läkare / en doktor", en: "a doctor" },
      { sv: "en sjuksköterska", en: "a nurse" },
      { sv: "ett apotek", en: "a pharmacy" },
      { sv: "en medicin", en: "a medicine" },
      { sv: "ett huvud", en: "a head" },
      { sv: "en hand", en: "a hand" },
      { sv: "en fot", en: "a foot" },
      { sv: "ryggen", en: "the back" },
      { sv: "det gör ont", en: "it hurts" },
    ],
    scenario: "You wake up feeling unwell and call to book an appointment at vårdcentralen.",
  },
  {
    id: "a2-perfekt",
    level: "A2",
    title: "Vad har du gjort?",
    theme: "Recent experiences using the perfect tense",
    grammarFocus: "Perfekt (har + supinum) — present perfect for actions linked to now",
    vocabulary: [
      { sv: "jag har gjort", en: "I have done" },
      { sv: "jag har varit", en: "I have been" },
      { sv: "jag har sett", en: "I have seen" },
      { sv: "jag har ätit", en: "I have eaten" },
      { sv: "jag har druckit", en: "I have drunk" },
      { sv: "jag har sovit", en: "I have slept" },
      { sv: "jag har bott", en: "I have lived" },
      { sv: "jag har rest", en: "I have travelled" },
      { sv: "jag har lärt mig", en: "I have learned" },
      { sv: "jag har provat", en: "I have tried" },
      { sv: "någonsin", en: "ever" },
      { sv: "aldrig", en: "never" },
      { sv: "redan", en: "already" },
      { sv: "ännu inte", en: "not yet" },
      { sv: "nyligen", en: "recently" },
      { sv: "flera gånger", en: "several times" },
    ],
    scenario: "A friend is curious about your life so far. They ask about places you've travelled, foods you've tried, and things you've never done.",
  },
  {
    id: "a2-futurum",
    level: "A2",
    title: "Vad ska du göra?",
    theme: "Plans, intentions, and the future tense",
    grammarFocus: "Futurum — ska (plan/intention) vs kommer att (prediction) vs present-as-future",
    vocabulary: [
      { sv: "jag ska", en: "I will / I'm going to (planned)" },
      { sv: "jag kommer att", en: "I will (prediction)" },
      { sv: "imorgon", en: "tomorrow" },
      { sv: "i övermorgon", en: "the day after tomorrow" },
      { sv: "i nästa vecka", en: "next week" },
      { sv: "i sommar", en: "this summer" },
      { sv: "snart", en: "soon" },
      { sv: "senare", en: "later" },
      { sv: "att planera", en: "to plan" },
      { sv: "en plan", en: "a plan" },
      { sv: "att tänka göra", en: "to plan/intend to do" },
      { sv: "kanske", en: "maybe" },
      { sv: "förmodligen", en: "probably" },
      { sv: "definitivt", en: "definitely" },
      { sv: "en framtid", en: "a future" },
    ],
    scenario: "A colleague asks about your weekend plans and what you'll do during your upcoming holiday.",
  },
  {
    id: "a2-8",
    level: "A2",
    title: "Fritid och intressen",
    theme: "Hobbies, free time, and preferences",
    grammarFocus: "Expressing preference (att tycka om, att gilla, hellre, helst)",
    vocabulary: [
      { sv: "en fritid", en: "free time" },
      { sv: "ett intresse", en: "an interest / hobby" },
      { sv: "att tycka om", en: "to like" },
      { sv: "att gilla", en: "to like" },
      { sv: "att älska", en: "to love" },
      { sv: "att hata", en: "to hate" },
      { sv: "hellre", en: "rather / preferably" },
      { sv: "helst", en: "most preferably" },
      { sv: "att läsa", en: "to read" },
      { sv: "att titta på film", en: "to watch films" },
      { sv: "att lyssna på musik", en: "to listen to music" },
      { sv: "att träna", en: "to exercise" },
      { sv: "att laga mat", en: "to cook" },
      { sv: "att resa", en: "to travel" },
      { sv: "en serie", en: "a TV series" },
    ],
    scenario: "You're getting to know someone on a first date. They ask what you do for fun.",
  },

  // ── B1 — intermediate preview ─────────────────────────────────
  {
    id: "b1-1",
    level: "B1",
    title: "Åsikter och argument",
    theme: "Sharing opinions and disagreeing politely",
    grammarFocus: "Subordinate clauses with att, eftersom, fastän — and word-order changes",
    vocabulary: [
      { sv: "en åsikt", en: "an opinion" },
      { sv: "att tycka att…", en: "to think that…" },
      { sv: "att tro att…", en: "to believe that…" },
      { sv: "jag håller med", en: "I agree" },
      { sv: "jag håller inte med", en: "I disagree" },
      { sv: "däremot", en: "on the other hand" },
      { sv: "å andra sidan", en: "on the other hand (lit.)" },
      { sv: "eftersom", en: "because" },
      { sv: "fastän", en: "although" },
      { sv: "trots att", en: "despite the fact that" },
      { sv: "att argumentera", en: "to argue / make a case" },
      { sv: "att övertyga", en: "to convince" },
      { sv: "ett exempel", en: "an example" },
      { sv: "till exempel", en: "for example" },
    ],
    scenario: "A friend claims that life in Sweden is generally less stressful than in Australia. Discuss whether you agree.",
  },
  {
    id: "b1-tenses",
    level: "B1",
    title: "Tidsformer i berättelser",
    theme: "Mixing tenses when telling stories about the past",
    grammarFocus: "Switching between preteritum, perfekt, and pluskvamperfekt naturally in narration",
    vocabulary: [
      { sv: "först", en: "first" },
      { sv: "sedan", en: "then" },
      { sv: "efteråt", en: "afterwards" },
      { sv: "innan", en: "before" },
      { sv: "när", en: "when" },
      { sv: "medan", en: "while" },
      { sv: "plötsligt", en: "suddenly" },
      { sv: "till slut", en: "in the end / finally" },
      { sv: "jag hade redan…", en: "I had already…" },
      { sv: "jag hade aldrig…", en: "I had never…" },
      { sv: "det visade sig att…", en: "it turned out that…" },
      { sv: "som tur var", en: "luckily" },
      { sv: "tyvärr", en: "unfortunately" },
      { sv: "en upplevelse", en: "an experience" },
      { sv: "en berättelse", en: "a story" },
    ],
    scenario: "You're telling a friend about a memorable trip — what had happened before it, what you did during, and how it ended.",
  },
  {
    id: "b1-2",
    level: "B1",
    title: "Nyheter och samhälle",
    theme: "News, politics, and society",
    grammarFocus: "Passive voice (s-form and bli-form) for news-style language",
    vocabulary: [
      { sv: "nyheter", en: "news" },
      { sv: "en tidning", en: "a newspaper" },
      { sv: "en artikel", en: "an article" },
      { sv: "ett samhälle", en: "a society" },
      { sv: "regeringen", en: "the government" },
      { sv: "ett val", en: "an election" },
      { sv: "att rösta", en: "to vote" },
      { sv: "en politiker", en: "a politician" },
      { sv: "en skatt", en: "a tax" },
      { sv: "ett problem", en: "a problem" },
      { sv: "en lösning", en: "a solution" },
      { sv: "att diskutera", en: "to discuss" },
      { sv: "viktig", en: "important" },
      { sv: "allvarlig", en: "serious" },
    ],
    scenario: "Discussing a news headline you saw this morning about Swedish housing policy.",
  },
];

export function lessonContext(lesson) {
  const vocabLines = lesson.vocabulary
    .map(v => `  - ${v.sv} (${v.en})`)
    .join("\n");

  return `
MODE: Structured lesson.

LESSON CONTEXT (level ${lesson.level}): ${lesson.title}
THEME: ${lesson.theme}
GRAMMAR FOCUS: ${lesson.grammarFocus}
SCENARIO: ${lesson.scenario}

TARGET VOCABULARY (weave these into next_question organically across turns):
${vocabLines}

LESSON-SPECIFIC RULES
- On the very first turn (when the user message is "Börja lektionen."), the what_was_good and what_needs_work arrays MUST be []. The next_question sets the scene for the scenario in 1-2 Swedish sentences and then asks an opening question.
- Use the target vocabulary and grammar focus naturally — not as a list.
- When you use a target-vocab word or phrase in next_question, wrap it in double asterisks like **ordet**. This helps the learner spot key words visually.
- When the learner has used at least 5 target words correctly across the lesson, congratulate them in next_question and suggest the next lesson.`;
}
